[project]
name = "kot-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.7.1",
    "typer>=0.12.5",
]
